Fixed bug where, upon logging in, if there are no existing schedules in the database an exception is thrown. This occurs because it attempts to set GlobalConfig.active_schedule to the 'sid' attribute of the first returned schedule in the database. Since the database is empty, however, this throws an AttributeError because the NoneType object has no attribute 'sid'.